# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Heritage Handbook
email: tim@discontents.com.au
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/digital-heritage-handbook" # the subpath of your site, e.g. /blog
url: "http://timsherratt.org/digital-heritage-handbook" # the base hostname & protocol for your site
twitter_username: wragge
github_username:  wragge

collections:
  activities:
    output: true
    permalink: '/:collection/:title/'
  lessons:
    output: true
    permalink: '/:collection/:title/'
  docs:
    output: true
    permalink: '/:collection/:title/'
  issues:
    output: true
    permalink: '/:collection/:title/'
  courses:
    output: true
    permalink: '/:collection/:title/'
  events:
    output: true
    permalink: '/:collection/:title/'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile']

gems:
  - jekyll-gist